### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by dtillner** [originlabs/graphql-postgres-subscriptions#12]
I'm using latest graphql@16.4.0 which is incompatible with peer and dev dependencies from package.json. 

My proposal is to update package.json to the following:

```diff
diff --git a/package.json b/package.json
index 315a39a..4f39c96 100644
--- a/package.json
+++ b/package.json
@@ -4,24 +4,24 @@
   "main": "index.js",
   "license": "MIT",
   "engines": {
-    "node": ">=6"
+    "node": ">=14"
   },
   "repository": {
     "type": "git",
     "url": "https://github.com/originlabs/graphql-postgres-subscriptions"
   },
   "peerDependencies": {
-    "graphql": "^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0"
+    "graphql": "^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0"
   },
   "dependencies": {
-    "graphql-subscriptions": "^1.2.1",
+    "graphql-subscriptions": "^2.0.0",
     "iterall": "^1.2.2",
-    "pg": "^8.5.1",
+    "pg": "^8.7.3",
     "pg-listen": "^1.7.0"
   },
   "devDependencies": {
-    "graphql": "^15.5.0",
-    "jest": "^26.6.3"
+    "graphql": "^16.4.0",
+    "jest": "^28.0.3"
   },
   "scripts": {
     "test": "jest --forceExit"
```

Would be nice to have updated packages in the repository.

Not sure what needs to be done in `Dockerfile` and `docker-compose.yml`

**Comment by flodev** [comment]
Hi @dtillner,

this would help us a lot. Could you create a PR or did you find an alternative solution in the meantime already?
@Jonahss what do you think about @dtillner proposal?

Best regards Florian

**Comment by chrisLovesCode** [comment]
Is this lib still maintained?

**Comment by flodev** [comment]
well there was some activity by @dtillner who created a PR and requested some other people to test the changes. no response from them though.

**Comment by flodev** [comment]
well there was some activity by @dtillner who created a PR and requested some other people to test the changes. no response from them though.

**Comment by chrisLovesCode** [comment]
> well there was some activity by @dtillner who created a PR and requested some other people to test the changes. no response from them though.

I can confirm @dtillner PR works, i checked out his pr in my current nestjs project with graphql subscriptions and implemented it there. it seems it's currently the only solution who works with lates graphql

**Comment by matziol** [comment]
Is there any chance to merge these changes?

**Comment by raqso** [comment]
Fixed in https://github.com/originlabs/graphql-postgres-subscriptions/pull/13 so this issue can be closed
