### ISSUE TITLE
Package can cause abrupt exit of Node process

### ISSUE THREAD

**Issue by spencerwilson** [originlabs/graphql-postgres-subscriptions#3]
Note: I haven't proven this is possible in practice.

It seems that [here](https://github.com/originlabs/graphql-postgres-subscriptions/blob/86e56c3a33cfadc128138505a3596e38524be607/postgres-pubsub.js#L38-L43) we use a handler that may return a promise that rejects. Specifically, it rejects if and only if the [underlying query](https://github.com/andywer/pg-listen/blob/90ad4882a2a09c88e4bd5ea1d7484a5a16dc352d/src/index.ts#L323) rejects.

If so, we should probably avoid this, since unhandled promises can cascade in a way that has varying degrees of unpleasant default behavior:
* Node < 15: Node logs warnings to the console
* Node >= 15: Node abruptly exits

Refs
* https://nodejs.org/docs/latest-v16.x/api/events.html#events_capture_rejections_of_promises
* https://nodejs.org/docs/latest-v16.x/api/cli.html#cli_unhandled_rejections_mode
* https://nodejs.org/docs/latest-v16.x/api/process.html#process_event_uncaughtexception

**Comment by Jonahss** [comment]
Ooh yeah. Good catch.
Are you in a position to submit a PR to fix the issue?

**Comment by spencerwilson** [comment]
I think so. If I don't show up with something within a few days, consider it free for the taking again 😄

**Comment by Jonahss** [comment]
Thanks!
