### ISSUE TITLE
No way to detect `publish` failures in-band; overloaded 'error' event

### ISSUE THREAD

**Issue by spencerwilson** [originlabs/graphql-postgres-subscriptions#6]
We'd like to write code like
```js
// pubSub: PostgresPubSub instance
try {
  await pubSub.publish('someTrigger', { my: 'payload' });
} catch (err) {
  return;
}

doThingOnlyIfPubSubSucceeded();
```

But that's not readily possible, as the promise returned from `publish` surely fulfills, with `true`: https://github.com/originlabs/graphql-postgres-subscriptions/blob/86e56c3a33cfadc128138505a3596e38524be607/postgres-pubsub.js#L57-L62

The above implementation also has another issue: in reusing the `'error'` event on pg-listen's EventEmitter, listeners on that event have no way of distinguishing between two different kinds of errors:
- The kind pg-listen emits: those indicating "fatal" errors on the pg-listen instance. In our app, we plan to reboot our application when this happens.
- The kind this library emits: those indicating a single `NOTIFY` query failed. In our app, we'd like to respond to these failures at the site of the `publish`.

## Background

The PubSubEngine interface recognized that in the general case publishing data to a pub/sub topic is fallible, and so it had `publish` return `Promise<void>` rather than just `void`: https://github.com/apollographql/graphql-subscriptions/blob/a5ad04439eb5eaaa3a7daaa1cccdb60a479006e4/src/pubsub-engine.ts#L4

For some reason, though, [graphql-postgres-subscriptions](https://www.npmjs.com/package/graphql-postgres-subscriptions) always returned `true`: https://github.com/GraphQLCollege/graphql-postgres-subscriptions/blob/46113aa0a5254b1c865069b11be448b2a120094b/postgres-pubsub.js#L24-L27

I imagine that @originlabs/graphql-postgres-subscriptions-retry, in its goal to be a drop-in replacement for graphql-postgres-subscriptions, preserved that. FWIW, other distributed PubSubEngine implementations like the ones for [Redis](https://github.com/davidyaha/graphql-redis-subscriptions/blob/41486fd080da56d54faf0ebe161596d5c635bd9c/src/redis-pubsub.ts#L81-L83) and [NATS](https://github.com/moonwalker/graphql-nats-subscriptions/blob/8f023b2b558494e7675d31fdb74844ba891dcd35/src/nats-pubsub.ts#L16-L18) _can_ fail during `publish`.

## Proposal

Would you be open to the following patch?

```diff
diff --git a/postgres-pubsub.js b/postgres-pubsub.js
index 6f0417b..30072bc 100644
--- a/postgres-pubsub.js
+++ b/postgres-pubsub.js
@@ -75,12 +75,7 @@ class PostgresPubSub extends PubSub {
       return false;
     }
 
-    try {
-      await this.pgListen.notify(triggerName, payload);
-    } catch (e) {
-      this.pgListen.events.emit('error', e)
-    }
-    return true;
+    return this.pgListen.notify(triggerName, payload);
   }
   async subscribe(triggerName, onMessage) {
     const callback = message => {
```
That would solve the two problems above by not overloading the meaning of `'error'` events and also give applications a chance to handle publish failures in-band. The tradeoff is that this library would cease to be a drop-in replacement graphql-postgres-subscriptions. I guess it comes down to: what are the goals for this fork? Do you more want it to be

- a reliability-focused Postgres LISTEN/NOTIFY-based PubSubEngine implementation; exclusive-or...
- a more reliable version of graphql-postgres-subscriptions.

FWIW our app was a greenfield one so compatibility wasn't super valuable to us.

**Comment by Jonahss** [comment]
> - a reliability-focused Postgres LISTEN/NOTIFY-based PubSubEngine implementation; exclusive-or...
> - a more reliable version of graphql-postgres-subscriptions.

More the latter, because we already broke the compatibility a little bit, by adding a few additional requirements to initialize everything.
I wasn't too satisfied with the original implementation's design decisions, and you might be mistaking my laziness for an attempt to keep drop-in compatibility ;)

Returning the result is much better than returning `true`. I also looked at uses of the original library, and the return values weren't being used anyways.

The error event was also me being lazy. I think I added that when I ran into an issue with messages being too long. If you send too many characters, the notify fails. Maybe we should add a test for that....

Send a PR for this change!
